name: Deploy to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: main
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ vars.AZURE_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add VM to known_hosts
        run: |
          ssh-keyscan -H ${{ vars.AZURE_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to Azure VM over SSH
        run: |
          ssh -i ~/.ssh/id_rsa -l "${{ vars.AZURE_USER }}" "${{ vars.AZURE_HOST }}" "
            git config --global url.'https://${{ vars.GH_PAT }}:x-oauth-basic@github.com/'.insteadOf 'https://github.com/'
            cd ~/url-shortener &&
            git fetch --all &&
            git reset --hard origin/main &&
            docker build -t url-shortener:latest . &&
            docker rm -f url-shortener || true &&
            docker run -d -p 8081:8080 \
              --name url-shortener \
              --restart unless-stopped \
              -e ASPNETCORE_ENVIRONMENT=Production \
              -e ASPNETCORE_URLS=http://+:8080 \
              -e AZURE_KEYVAULT_URL='${{ vars.AZURE_KEYVAULT_URL }}' \
              -e AZURE_SECRET_NAME_CONNECTIONSTRING='${{ vars.AZURE_SECRET_NAME_CONNECTIONSTRING }}' \
              -e AZURE_CLIENT_ID='${{ vars.AZURE_CLIENT_ID }}' \
              -e AZURE_CLIENT_SECRET='${{ vars.AZURE_CLIENT_SECRET }}' \
              -e AZURE_TENANT_ID='${{ vars.AZURE_TENANT_ID }}' \
              -e Jwt__Key='${{ vars.JWT_SECRET }}' \
              -e Jwt__Issuer='${{ vars.JWT_ISSUER }}' \
              -e Jwt__Audience='${{ vars.JWT_AUDIENCE }}' \
              url-shortener:latest
          "
